version: "3.1"

services:
  pg_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080